name: Publish Docker image
on:
  push:
    branches:
      - feature/*
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Validate Terraform code
      run: |
        terraform fmt -diff
        terraform validate